### ISSUE TITLE
音频如果较长用户点击进度条的时候没加载到哪怎样给用户友好提示？

### ISSUE THREAD

**Issue by bruce-zhang932** [zhangwei900808/AcPlayer#1]
我做的微信音频播放用的是您的播放插件，有个问题是，当点击播放时(点击进度条)音频如果没有加载完，就停在哪了很不美观，我怎样在加载的过程中加一个加载中的动画效果呢？

**Comment by zhangwei900808** [comment]
不好意思才看到你的问题，
你可以使用：audio|video.networkState试试，
表示音频/视频元素的当前网络状态：
0 = NETWORK_EMPTY - 音频/视频尚未初始化
1 = NETWORK_IDLE - 音频/视频是活动的且已选取资源，但并未使用网络
2 = NETWORK_LOADING - 浏览器正在下载数据
3 = NETWORK_NO_SOURCE - 未找到音频/视频来源

结合progress事件：

```js
audio|video.addEventListener("progress", function()
  {
  //SomeJavaScriptCode
  }
);
```
